package com.unbank.mybatis.vo;

public class BhiConstruction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.id
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_department
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_people
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_people_job
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionPeopleJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_tel
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_fax
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_postcode
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_detail_address
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionDetailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_construction.construction_weburl
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String constructionWeburl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.id
     *
     * @return the value of bhi_construction.id
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.id
     *
     * @param id the value for bhi_construction.id
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_department
     *
     * @return the value of bhi_construction.construction_department
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionDepartment() {
        return constructionDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_department
     *
     * @param constructionDepartment the value for bhi_construction.construction_department
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionDepartment(String constructionDepartment) {
        this.constructionDepartment = constructionDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_people
     *
     * @return the value of bhi_construction.construction_people
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionPeople() {
        return constructionPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_people
     *
     * @param constructionPeople the value for bhi_construction.construction_people
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionPeople(String constructionPeople) {
        this.constructionPeople = constructionPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_people_job
     *
     * @return the value of bhi_construction.construction_people_job
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionPeopleJob() {
        return constructionPeopleJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_people_job
     *
     * @param constructionPeopleJob the value for bhi_construction.construction_people_job
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionPeopleJob(String constructionPeopleJob) {
        this.constructionPeopleJob = constructionPeopleJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_tel
     *
     * @return the value of bhi_construction.construction_tel
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionTel() {
        return constructionTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_tel
     *
     * @param constructionTel the value for bhi_construction.construction_tel
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionTel(String constructionTel) {
        this.constructionTel = constructionTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_fax
     *
     * @return the value of bhi_construction.construction_fax
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionFax() {
        return constructionFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_fax
     *
     * @param constructionFax the value for bhi_construction.construction_fax
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionFax(String constructionFax) {
        this.constructionFax = constructionFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_postcode
     *
     * @return the value of bhi_construction.construction_postcode
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionPostcode() {
        return constructionPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_postcode
     *
     * @param constructionPostcode the value for bhi_construction.construction_postcode
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionPostcode(String constructionPostcode) {
        this.constructionPostcode = constructionPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_detail_address
     *
     * @return the value of bhi_construction.construction_detail_address
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionDetailAddress() {
        return constructionDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_detail_address
     *
     * @param constructionDetailAddress the value for bhi_construction.construction_detail_address
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionDetailAddress(String constructionDetailAddress) {
        this.constructionDetailAddress = constructionDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_construction.construction_weburl
     *
     * @return the value of bhi_construction.construction_weburl
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getConstructionWeburl() {
        return constructionWeburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_construction.construction_weburl
     *
     * @param constructionWeburl the value for bhi_construction.construction_weburl
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setConstructionWeburl(String constructionWeburl) {
        this.constructionWeburl = constructionWeburl;
    }
}