package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiConstructionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public BhiConstructionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentIsNull() {
            addCriterion("construction_department is null");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentIsNotNull() {
            addCriterion("construction_department is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentEqualTo(String value) {
            addCriterion("construction_department =", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentNotEqualTo(String value) {
            addCriterion("construction_department <>", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentGreaterThan(String value) {
            addCriterion("construction_department >", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("construction_department >=", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentLessThan(String value) {
            addCriterion("construction_department <", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentLessThanOrEqualTo(String value) {
            addCriterion("construction_department <=", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentLike(String value) {
            addCriterion("construction_department like", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentNotLike(String value) {
            addCriterion("construction_department not like", value, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentIn(List<String> values) {
            addCriterion("construction_department in", values, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentNotIn(List<String> values) {
            addCriterion("construction_department not in", values, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentBetween(String value1, String value2) {
            addCriterion("construction_department between", value1, value2, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionDepartmentNotBetween(String value1, String value2) {
            addCriterion("construction_department not between", value1, value2, "constructionDepartment");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleIsNull() {
            addCriterion("construction_people is null");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleIsNotNull() {
            addCriterion("construction_people is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleEqualTo(String value) {
            addCriterion("construction_people =", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleNotEqualTo(String value) {
            addCriterion("construction_people <>", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleGreaterThan(String value) {
            addCriterion("construction_people >", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("construction_people >=", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleLessThan(String value) {
            addCriterion("construction_people <", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleLessThanOrEqualTo(String value) {
            addCriterion("construction_people <=", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleLike(String value) {
            addCriterion("construction_people like", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleNotLike(String value) {
            addCriterion("construction_people not like", value, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleIn(List<String> values) {
            addCriterion("construction_people in", values, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleNotIn(List<String> values) {
            addCriterion("construction_people not in", values, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleBetween(String value1, String value2) {
            addCriterion("construction_people between", value1, value2, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleNotBetween(String value1, String value2) {
            addCriterion("construction_people not between", value1, value2, "constructionPeople");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobIsNull() {
            addCriterion("construction_people_job is null");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobIsNotNull() {
            addCriterion("construction_people_job is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobEqualTo(String value) {
            addCriterion("construction_people_job =", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobNotEqualTo(String value) {
            addCriterion("construction_people_job <>", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobGreaterThan(String value) {
            addCriterion("construction_people_job >", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobGreaterThanOrEqualTo(String value) {
            addCriterion("construction_people_job >=", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobLessThan(String value) {
            addCriterion("construction_people_job <", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobLessThanOrEqualTo(String value) {
            addCriterion("construction_people_job <=", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobLike(String value) {
            addCriterion("construction_people_job like", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobNotLike(String value) {
            addCriterion("construction_people_job not like", value, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobIn(List<String> values) {
            addCriterion("construction_people_job in", values, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobNotIn(List<String> values) {
            addCriterion("construction_people_job not in", values, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobBetween(String value1, String value2) {
            addCriterion("construction_people_job between", value1, value2, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionPeopleJobNotBetween(String value1, String value2) {
            addCriterion("construction_people_job not between", value1, value2, "constructionPeopleJob");
            return (Criteria) this;
        }

        public Criteria andConstructionTelIsNull() {
            addCriterion("construction_tel is null");
            return (Criteria) this;
        }

        public Criteria andConstructionTelIsNotNull() {
            addCriterion("construction_tel is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionTelEqualTo(String value) {
            addCriterion("construction_tel =", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelNotEqualTo(String value) {
            addCriterion("construction_tel <>", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelGreaterThan(String value) {
            addCriterion("construction_tel >", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelGreaterThanOrEqualTo(String value) {
            addCriterion("construction_tel >=", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelLessThan(String value) {
            addCriterion("construction_tel <", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelLessThanOrEqualTo(String value) {
            addCriterion("construction_tel <=", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelLike(String value) {
            addCriterion("construction_tel like", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelNotLike(String value) {
            addCriterion("construction_tel not like", value, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelIn(List<String> values) {
            addCriterion("construction_tel in", values, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelNotIn(List<String> values) {
            addCriterion("construction_tel not in", values, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelBetween(String value1, String value2) {
            addCriterion("construction_tel between", value1, value2, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionTelNotBetween(String value1, String value2) {
            addCriterion("construction_tel not between", value1, value2, "constructionTel");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxIsNull() {
            addCriterion("construction_fax is null");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxIsNotNull() {
            addCriterion("construction_fax is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxEqualTo(String value) {
            addCriterion("construction_fax =", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxNotEqualTo(String value) {
            addCriterion("construction_fax <>", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxGreaterThan(String value) {
            addCriterion("construction_fax >", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxGreaterThanOrEqualTo(String value) {
            addCriterion("construction_fax >=", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxLessThan(String value) {
            addCriterion("construction_fax <", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxLessThanOrEqualTo(String value) {
            addCriterion("construction_fax <=", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxLike(String value) {
            addCriterion("construction_fax like", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxNotLike(String value) {
            addCriterion("construction_fax not like", value, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxIn(List<String> values) {
            addCriterion("construction_fax in", values, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxNotIn(List<String> values) {
            addCriterion("construction_fax not in", values, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxBetween(String value1, String value2) {
            addCriterion("construction_fax between", value1, value2, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionFaxNotBetween(String value1, String value2) {
            addCriterion("construction_fax not between", value1, value2, "constructionFax");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeIsNull() {
            addCriterion("construction_postcode is null");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeIsNotNull() {
            addCriterion("construction_postcode is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeEqualTo(String value) {
            addCriterion("construction_postcode =", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeNotEqualTo(String value) {
            addCriterion("construction_postcode <>", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeGreaterThan(String value) {
            addCriterion("construction_postcode >", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("construction_postcode >=", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeLessThan(String value) {
            addCriterion("construction_postcode <", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeLessThanOrEqualTo(String value) {
            addCriterion("construction_postcode <=", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeLike(String value) {
            addCriterion("construction_postcode like", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeNotLike(String value) {
            addCriterion("construction_postcode not like", value, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeIn(List<String> values) {
            addCriterion("construction_postcode in", values, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeNotIn(List<String> values) {
            addCriterion("construction_postcode not in", values, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeBetween(String value1, String value2) {
            addCriterion("construction_postcode between", value1, value2, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionPostcodeNotBetween(String value1, String value2) {
            addCriterion("construction_postcode not between", value1, value2, "constructionPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressIsNull() {
            addCriterion("construction_detail_address is null");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressIsNotNull() {
            addCriterion("construction_detail_address is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressEqualTo(String value) {
            addCriterion("construction_detail_address =", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressNotEqualTo(String value) {
            addCriterion("construction_detail_address <>", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressGreaterThan(String value) {
            addCriterion("construction_detail_address >", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("construction_detail_address >=", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressLessThan(String value) {
            addCriterion("construction_detail_address <", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressLessThanOrEqualTo(String value) {
            addCriterion("construction_detail_address <=", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressLike(String value) {
            addCriterion("construction_detail_address like", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressNotLike(String value) {
            addCriterion("construction_detail_address not like", value, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressIn(List<String> values) {
            addCriterion("construction_detail_address in", values, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressNotIn(List<String> values) {
            addCriterion("construction_detail_address not in", values, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressBetween(String value1, String value2) {
            addCriterion("construction_detail_address between", value1, value2, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionDetailAddressNotBetween(String value1, String value2) {
            addCriterion("construction_detail_address not between", value1, value2, "constructionDetailAddress");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlIsNull() {
            addCriterion("construction_weburl is null");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlIsNotNull() {
            addCriterion("construction_weburl is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlEqualTo(String value) {
            addCriterion("construction_weburl =", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlNotEqualTo(String value) {
            addCriterion("construction_weburl <>", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlGreaterThan(String value) {
            addCriterion("construction_weburl >", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlGreaterThanOrEqualTo(String value) {
            addCriterion("construction_weburl >=", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlLessThan(String value) {
            addCriterion("construction_weburl <", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlLessThanOrEqualTo(String value) {
            addCriterion("construction_weburl <=", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlLike(String value) {
            addCriterion("construction_weburl like", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlNotLike(String value) {
            addCriterion("construction_weburl not like", value, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlIn(List<String> values) {
            addCriterion("construction_weburl in", values, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlNotIn(List<String> values) {
            addCriterion("construction_weburl not in", values, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlBetween(String value1, String value2) {
            addCriterion("construction_weburl between", value1, value2, "constructionWeburl");
            return (Criteria) this;
        }

        public Criteria andConstructionWeburlNotBetween(String value1, String value2) {
            addCriterion("construction_weburl not between", value1, value2, "constructionWeburl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_construction
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}