package com.unbank.mybatis.vo;

public class BhiDesign {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_design.design_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String designWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.id
	 * @return  the value of bhi_design.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.id
	 * @param id  the value for bhi_design.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_department
	 * @return  the value of bhi_design.design_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignDepartment() {
		return designDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_department
	 * @param designDepartment  the value for bhi_design.design_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignDepartment(String designDepartment) {
		this.designDepartment = designDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_people
	 * @return  the value of bhi_design.design_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignPeople() {
		return designPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_people
	 * @param designPeople  the value for bhi_design.design_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignPeople(String designPeople) {
		this.designPeople = designPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_people_job
	 * @return  the value of bhi_design.design_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignPeopleJob() {
		return designPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_people_job
	 * @param designPeopleJob  the value for bhi_design.design_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignPeopleJob(String designPeopleJob) {
		this.designPeopleJob = designPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_tel
	 * @return  the value of bhi_design.design_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignTel() {
		return designTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_tel
	 * @param designTel  the value for bhi_design.design_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignTel(String designTel) {
		this.designTel = designTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_fax
	 * @return  the value of bhi_design.design_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignFax() {
		return designFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_fax
	 * @param designFax  the value for bhi_design.design_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignFax(String designFax) {
		this.designFax = designFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_postcode
	 * @return  the value of bhi_design.design_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignPostcode() {
		return designPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_postcode
	 * @param designPostcode  the value for bhi_design.design_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignPostcode(String designPostcode) {
		this.designPostcode = designPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_detail_address
	 * @return  the value of bhi_design.design_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignDetailAddress() {
		return designDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_detail_address
	 * @param designDetailAddress  the value for bhi_design.design_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignDetailAddress(String designDetailAddress) {
		this.designDetailAddress = designDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_design.design_weburl
	 * @return  the value of bhi_design.design_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getDesignWeburl() {
		return designWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_design.design_weburl
	 * @param designWeburl  the value for bhi_design.design_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDesignWeburl(String designWeburl) {
		this.designWeburl = designWeburl;
	}
}