package com.unbank.mybatis.vo;

public class BhiEnvironmentalAssessment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.id
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_department
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_people
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_people_job
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentPeopleJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_tel
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_fax
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_postcode
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_detail_address
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentDetailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_environmental_assessment.environmental_assessment_weburl
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    private String environmentalAssessmentWeburl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.id
     *
     * @return the value of bhi_environmental_assessment.id
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.id
     *
     * @param id the value for bhi_environmental_assessment.id
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_department
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_department
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentDepartment() {
        return environmentalAssessmentDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_department
     *
     * @param environmentalAssessmentDepartment the value for bhi_environmental_assessment.environmental_assessment_department
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentDepartment(String environmentalAssessmentDepartment) {
        this.environmentalAssessmentDepartment = environmentalAssessmentDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_people
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_people
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentPeople() {
        return environmentalAssessmentPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_people
     *
     * @param environmentalAssessmentPeople the value for bhi_environmental_assessment.environmental_assessment_people
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentPeople(String environmentalAssessmentPeople) {
        this.environmentalAssessmentPeople = environmentalAssessmentPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_people_job
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_people_job
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentPeopleJob() {
        return environmentalAssessmentPeopleJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_people_job
     *
     * @param environmentalAssessmentPeopleJob the value for bhi_environmental_assessment.environmental_assessment_people_job
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentPeopleJob(String environmentalAssessmentPeopleJob) {
        this.environmentalAssessmentPeopleJob = environmentalAssessmentPeopleJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_tel
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_tel
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentTel() {
        return environmentalAssessmentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_tel
     *
     * @param environmentalAssessmentTel the value for bhi_environmental_assessment.environmental_assessment_tel
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentTel(String environmentalAssessmentTel) {
        this.environmentalAssessmentTel = environmentalAssessmentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_fax
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_fax
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentFax() {
        return environmentalAssessmentFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_fax
     *
     * @param environmentalAssessmentFax the value for bhi_environmental_assessment.environmental_assessment_fax
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentFax(String environmentalAssessmentFax) {
        this.environmentalAssessmentFax = environmentalAssessmentFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_postcode
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_postcode
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentPostcode() {
        return environmentalAssessmentPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_postcode
     *
     * @param environmentalAssessmentPostcode the value for bhi_environmental_assessment.environmental_assessment_postcode
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentPostcode(String environmentalAssessmentPostcode) {
        this.environmentalAssessmentPostcode = environmentalAssessmentPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_detail_address
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_detail_address
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentDetailAddress() {
        return environmentalAssessmentDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_detail_address
     *
     * @param environmentalAssessmentDetailAddress the value for bhi_environmental_assessment.environmental_assessment_detail_address
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentDetailAddress(String environmentalAssessmentDetailAddress) {
        this.environmentalAssessmentDetailAddress = environmentalAssessmentDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_environmental_assessment.environmental_assessment_weburl
     *
     * @return the value of bhi_environmental_assessment.environmental_assessment_weburl
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getEnvironmentalAssessmentWeburl() {
        return environmentalAssessmentWeburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_environmental_assessment.environmental_assessment_weburl
     *
     * @param environmentalAssessmentWeburl the value for bhi_environmental_assessment.environmental_assessment_weburl
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setEnvironmentalAssessmentWeburl(String environmentalAssessmentWeburl) {
        this.environmentalAssessmentWeburl = environmentalAssessmentWeburl;
    }
}