package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiEnvironmentalAssessmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public BhiEnvironmentalAssessmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentIsNull() {
            addCriterion("environmental_assessment_department is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentIsNotNull() {
            addCriterion("environmental_assessment_department is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentEqualTo(String value) {
            addCriterion("environmental_assessment_department =", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentNotEqualTo(String value) {
            addCriterion("environmental_assessment_department <>", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentGreaterThan(String value) {
            addCriterion("environmental_assessment_department >", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_department >=", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentLessThan(String value) {
            addCriterion("environmental_assessment_department <", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_department <=", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentLike(String value) {
            addCriterion("environmental_assessment_department like", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentNotLike(String value) {
            addCriterion("environmental_assessment_department not like", value, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentIn(List<String> values) {
            addCriterion("environmental_assessment_department in", values, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentNotIn(List<String> values) {
            addCriterion("environmental_assessment_department not in", values, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentBetween(String value1, String value2) {
            addCriterion("environmental_assessment_department between", value1, value2, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDepartmentNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_department not between", value1, value2, "environmentalAssessmentDepartment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleIsNull() {
            addCriterion("environmental_assessment_people is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleIsNotNull() {
            addCriterion("environmental_assessment_people is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleEqualTo(String value) {
            addCriterion("environmental_assessment_people =", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleNotEqualTo(String value) {
            addCriterion("environmental_assessment_people <>", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleGreaterThan(String value) {
            addCriterion("environmental_assessment_people >", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_people >=", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleLessThan(String value) {
            addCriterion("environmental_assessment_people <", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_people <=", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleLike(String value) {
            addCriterion("environmental_assessment_people like", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleNotLike(String value) {
            addCriterion("environmental_assessment_people not like", value, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleIn(List<String> values) {
            addCriterion("environmental_assessment_people in", values, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleNotIn(List<String> values) {
            addCriterion("environmental_assessment_people not in", values, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleBetween(String value1, String value2) {
            addCriterion("environmental_assessment_people between", value1, value2, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_people not between", value1, value2, "environmentalAssessmentPeople");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobIsNull() {
            addCriterion("environmental_assessment_people_job is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobIsNotNull() {
            addCriterion("environmental_assessment_people_job is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobEqualTo(String value) {
            addCriterion("environmental_assessment_people_job =", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobNotEqualTo(String value) {
            addCriterion("environmental_assessment_people_job <>", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobGreaterThan(String value) {
            addCriterion("environmental_assessment_people_job >", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_people_job >=", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobLessThan(String value) {
            addCriterion("environmental_assessment_people_job <", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_people_job <=", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobLike(String value) {
            addCriterion("environmental_assessment_people_job like", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobNotLike(String value) {
            addCriterion("environmental_assessment_people_job not like", value, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobIn(List<String> values) {
            addCriterion("environmental_assessment_people_job in", values, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobNotIn(List<String> values) {
            addCriterion("environmental_assessment_people_job not in", values, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobBetween(String value1, String value2) {
            addCriterion("environmental_assessment_people_job between", value1, value2, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPeopleJobNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_people_job not between", value1, value2, "environmentalAssessmentPeopleJob");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelIsNull() {
            addCriterion("environmental_assessment_tel is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelIsNotNull() {
            addCriterion("environmental_assessment_tel is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelEqualTo(String value) {
            addCriterion("environmental_assessment_tel =", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelNotEqualTo(String value) {
            addCriterion("environmental_assessment_tel <>", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelGreaterThan(String value) {
            addCriterion("environmental_assessment_tel >", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_tel >=", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelLessThan(String value) {
            addCriterion("environmental_assessment_tel <", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_tel <=", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelLike(String value) {
            addCriterion("environmental_assessment_tel like", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelNotLike(String value) {
            addCriterion("environmental_assessment_tel not like", value, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelIn(List<String> values) {
            addCriterion("environmental_assessment_tel in", values, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelNotIn(List<String> values) {
            addCriterion("environmental_assessment_tel not in", values, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelBetween(String value1, String value2) {
            addCriterion("environmental_assessment_tel between", value1, value2, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentTelNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_tel not between", value1, value2, "environmentalAssessmentTel");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxIsNull() {
            addCriterion("environmental_assessment_fax is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxIsNotNull() {
            addCriterion("environmental_assessment_fax is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxEqualTo(String value) {
            addCriterion("environmental_assessment_fax =", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxNotEqualTo(String value) {
            addCriterion("environmental_assessment_fax <>", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxGreaterThan(String value) {
            addCriterion("environmental_assessment_fax >", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_fax >=", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxLessThan(String value) {
            addCriterion("environmental_assessment_fax <", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_fax <=", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxLike(String value) {
            addCriterion("environmental_assessment_fax like", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxNotLike(String value) {
            addCriterion("environmental_assessment_fax not like", value, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxIn(List<String> values) {
            addCriterion("environmental_assessment_fax in", values, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxNotIn(List<String> values) {
            addCriterion("environmental_assessment_fax not in", values, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxBetween(String value1, String value2) {
            addCriterion("environmental_assessment_fax between", value1, value2, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentFaxNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_fax not between", value1, value2, "environmentalAssessmentFax");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeIsNull() {
            addCriterion("environmental_assessment_postcode is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeIsNotNull() {
            addCriterion("environmental_assessment_postcode is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeEqualTo(String value) {
            addCriterion("environmental_assessment_postcode =", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeNotEqualTo(String value) {
            addCriterion("environmental_assessment_postcode <>", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeGreaterThan(String value) {
            addCriterion("environmental_assessment_postcode >", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_postcode >=", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeLessThan(String value) {
            addCriterion("environmental_assessment_postcode <", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_postcode <=", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeLike(String value) {
            addCriterion("environmental_assessment_postcode like", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeNotLike(String value) {
            addCriterion("environmental_assessment_postcode not like", value, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeIn(List<String> values) {
            addCriterion("environmental_assessment_postcode in", values, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeNotIn(List<String> values) {
            addCriterion("environmental_assessment_postcode not in", values, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeBetween(String value1, String value2) {
            addCriterion("environmental_assessment_postcode between", value1, value2, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentPostcodeNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_postcode not between", value1, value2, "environmentalAssessmentPostcode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressIsNull() {
            addCriterion("environmental_assessment_detail_address is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressIsNotNull() {
            addCriterion("environmental_assessment_detail_address is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressEqualTo(String value) {
            addCriterion("environmental_assessment_detail_address =", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressNotEqualTo(String value) {
            addCriterion("environmental_assessment_detail_address <>", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressGreaterThan(String value) {
            addCriterion("environmental_assessment_detail_address >", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_detail_address >=", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressLessThan(String value) {
            addCriterion("environmental_assessment_detail_address <", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_detail_address <=", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressLike(String value) {
            addCriterion("environmental_assessment_detail_address like", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressNotLike(String value) {
            addCriterion("environmental_assessment_detail_address not like", value, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressIn(List<String> values) {
            addCriterion("environmental_assessment_detail_address in", values, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressNotIn(List<String> values) {
            addCriterion("environmental_assessment_detail_address not in", values, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressBetween(String value1, String value2) {
            addCriterion("environmental_assessment_detail_address between", value1, value2, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentDetailAddressNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_detail_address not between", value1, value2, "environmentalAssessmentDetailAddress");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlIsNull() {
            addCriterion("environmental_assessment_weburl is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlIsNotNull() {
            addCriterion("environmental_assessment_weburl is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlEqualTo(String value) {
            addCriterion("environmental_assessment_weburl =", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlNotEqualTo(String value) {
            addCriterion("environmental_assessment_weburl <>", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlGreaterThan(String value) {
            addCriterion("environmental_assessment_weburl >", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlGreaterThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_weburl >=", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlLessThan(String value) {
            addCriterion("environmental_assessment_weburl <", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlLessThanOrEqualTo(String value) {
            addCriterion("environmental_assessment_weburl <=", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlLike(String value) {
            addCriterion("environmental_assessment_weburl like", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlNotLike(String value) {
            addCriterion("environmental_assessment_weburl not like", value, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlIn(List<String> values) {
            addCriterion("environmental_assessment_weburl in", values, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlNotIn(List<String> values) {
            addCriterion("environmental_assessment_weburl not in", values, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlBetween(String value1, String value2) {
            addCriterion("environmental_assessment_weburl between", value1, value2, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }

        public Criteria andEnvironmentalAssessmentWeburlNotBetween(String value1, String value2) {
            addCriterion("environmental_assessment_weburl not between", value1, value2, "environmentalAssessmentWeburl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}