package com.unbank.mybatis.vo;

public class BhiFeasibilityStudy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_feasibility_study.feasibility_study_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String feasibilityStudyWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.id
	 * @return  the value of bhi_feasibility_study.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.id
	 * @param id  the value for bhi_feasibility_study.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_department
	 * @return  the value of bhi_feasibility_study.feasibility_study_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyDepartment() {
		return feasibilityStudyDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_department
	 * @param feasibilityStudyDepartment  the value for bhi_feasibility_study.feasibility_study_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyDepartment(String feasibilityStudyDepartment) {
		this.feasibilityStudyDepartment = feasibilityStudyDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_people
	 * @return  the value of bhi_feasibility_study.feasibility_study_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyPeople() {
		return feasibilityStudyPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_people
	 * @param feasibilityStudyPeople  the value for bhi_feasibility_study.feasibility_study_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyPeople(String feasibilityStudyPeople) {
		this.feasibilityStudyPeople = feasibilityStudyPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_people_job
	 * @return  the value of bhi_feasibility_study.feasibility_study_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyPeopleJob() {
		return feasibilityStudyPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_people_job
	 * @param feasibilityStudyPeopleJob  the value for bhi_feasibility_study.feasibility_study_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyPeopleJob(String feasibilityStudyPeopleJob) {
		this.feasibilityStudyPeopleJob = feasibilityStudyPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_tel
	 * @return  the value of bhi_feasibility_study.feasibility_study_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyTel() {
		return feasibilityStudyTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_tel
	 * @param feasibilityStudyTel  the value for bhi_feasibility_study.feasibility_study_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyTel(String feasibilityStudyTel) {
		this.feasibilityStudyTel = feasibilityStudyTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_fax
	 * @return  the value of bhi_feasibility_study.feasibility_study_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyFax() {
		return feasibilityStudyFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_fax
	 * @param feasibilityStudyFax  the value for bhi_feasibility_study.feasibility_study_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyFax(String feasibilityStudyFax) {
		this.feasibilityStudyFax = feasibilityStudyFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_postcode
	 * @return  the value of bhi_feasibility_study.feasibility_study_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyPostcode() {
		return feasibilityStudyPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_postcode
	 * @param feasibilityStudyPostcode  the value for bhi_feasibility_study.feasibility_study_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyPostcode(String feasibilityStudyPostcode) {
		this.feasibilityStudyPostcode = feasibilityStudyPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_detail_address
	 * @return  the value of bhi_feasibility_study.feasibility_study_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyDetailAddress() {
		return feasibilityStudyDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_detail_address
	 * @param feasibilityStudyDetailAddress  the value for bhi_feasibility_study.feasibility_study_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyDetailAddress(
			String feasibilityStudyDetailAddress) {
		this.feasibilityStudyDetailAddress = feasibilityStudyDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_feasibility_study.feasibility_study_weburl
	 * @return  the value of bhi_feasibility_study.feasibility_study_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFeasibilityStudyWeburl() {
		return feasibilityStudyWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_feasibility_study.feasibility_study_weburl
	 * @param feasibilityStudyWeburl  the value for bhi_feasibility_study.feasibility_study_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFeasibilityStudyWeburl(String feasibilityStudyWeburl) {
		this.feasibilityStudyWeburl = feasibilityStudyWeburl;
	}
}