package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiFeasibilityStudyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public BhiFeasibilityStudyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentIsNull() {
			addCriterion("feasibility_study_department is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentIsNotNull() {
			addCriterion("feasibility_study_department is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentEqualTo(String value) {
			addCriterion("feasibility_study_department =", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentNotEqualTo(String value) {
			addCriterion("feasibility_study_department <>", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentGreaterThan(String value) {
			addCriterion("feasibility_study_department >", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentGreaterThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_department >=", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentLessThan(String value) {
			addCriterion("feasibility_study_department <", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentLessThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_department <=", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentLike(String value) {
			addCriterion("feasibility_study_department like", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentNotLike(String value) {
			addCriterion("feasibility_study_department not like", value,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentIn(List<String> values) {
			addCriterion("feasibility_study_department in", values,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentNotIn(List<String> values) {
			addCriterion("feasibility_study_department not in", values,
					"feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_department between", value1,
					value2, "feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDepartmentNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_department not between", value1,
					value2, "feasibilityStudyDepartment");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleIsNull() {
			addCriterion("feasibility_study_people is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleIsNotNull() {
			addCriterion("feasibility_study_people is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleEqualTo(String value) {
			addCriterion("feasibility_study_people =", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleNotEqualTo(String value) {
			addCriterion("feasibility_study_people <>", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleGreaterThan(String value) {
			addCriterion("feasibility_study_people >", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleGreaterThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_people >=", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleLessThan(String value) {
			addCriterion("feasibility_study_people <", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleLessThanOrEqualTo(String value) {
			addCriterion("feasibility_study_people <=", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleLike(String value) {
			addCriterion("feasibility_study_people like", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleNotLike(String value) {
			addCriterion("feasibility_study_people not like", value,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleIn(List<String> values) {
			addCriterion("feasibility_study_people in", values,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleNotIn(List<String> values) {
			addCriterion("feasibility_study_people not in", values,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_people between", value1, value2,
					"feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_people not between", value1,
					value2, "feasibilityStudyPeople");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobIsNull() {
			addCriterion("feasibility_study_people_job is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobIsNotNull() {
			addCriterion("feasibility_study_people_job is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobEqualTo(String value) {
			addCriterion("feasibility_study_people_job =", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobNotEqualTo(String value) {
			addCriterion("feasibility_study_people_job <>", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobGreaterThan(String value) {
			addCriterion("feasibility_study_people_job >", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobGreaterThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_people_job >=", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobLessThan(String value) {
			addCriterion("feasibility_study_people_job <", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobLessThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_people_job <=", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobLike(String value) {
			addCriterion("feasibility_study_people_job like", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobNotLike(String value) {
			addCriterion("feasibility_study_people_job not like", value,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobIn(List<String> values) {
			addCriterion("feasibility_study_people_job in", values,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobNotIn(List<String> values) {
			addCriterion("feasibility_study_people_job not in", values,
					"feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_people_job between", value1,
					value2, "feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPeopleJobNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_people_job not between", value1,
					value2, "feasibilityStudyPeopleJob");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelIsNull() {
			addCriterion("feasibility_study_tel is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelIsNotNull() {
			addCriterion("feasibility_study_tel is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelEqualTo(String value) {
			addCriterion("feasibility_study_tel =", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelNotEqualTo(String value) {
			addCriterion("feasibility_study_tel <>", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelGreaterThan(String value) {
			addCriterion("feasibility_study_tel >", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelGreaterThanOrEqualTo(String value) {
			addCriterion("feasibility_study_tel >=", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelLessThan(String value) {
			addCriterion("feasibility_study_tel <", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelLessThanOrEqualTo(String value) {
			addCriterion("feasibility_study_tel <=", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelLike(String value) {
			addCriterion("feasibility_study_tel like", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelNotLike(String value) {
			addCriterion("feasibility_study_tel not like", value,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelIn(List<String> values) {
			addCriterion("feasibility_study_tel in", values,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelNotIn(List<String> values) {
			addCriterion("feasibility_study_tel not in", values,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_tel between", value1, value2,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyTelNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_tel not between", value1, value2,
					"feasibilityStudyTel");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxIsNull() {
			addCriterion("feasibility_study_fax is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxIsNotNull() {
			addCriterion("feasibility_study_fax is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxEqualTo(String value) {
			addCriterion("feasibility_study_fax =", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxNotEqualTo(String value) {
			addCriterion("feasibility_study_fax <>", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxGreaterThan(String value) {
			addCriterion("feasibility_study_fax >", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxGreaterThanOrEqualTo(String value) {
			addCriterion("feasibility_study_fax >=", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxLessThan(String value) {
			addCriterion("feasibility_study_fax <", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxLessThanOrEqualTo(String value) {
			addCriterion("feasibility_study_fax <=", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxLike(String value) {
			addCriterion("feasibility_study_fax like", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxNotLike(String value) {
			addCriterion("feasibility_study_fax not like", value,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxIn(List<String> values) {
			addCriterion("feasibility_study_fax in", values,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxNotIn(List<String> values) {
			addCriterion("feasibility_study_fax not in", values,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_fax between", value1, value2,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyFaxNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_fax not between", value1, value2,
					"feasibilityStudyFax");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeIsNull() {
			addCriterion("feasibility_study_postcode is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeIsNotNull() {
			addCriterion("feasibility_study_postcode is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeEqualTo(String value) {
			addCriterion("feasibility_study_postcode =", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeNotEqualTo(String value) {
			addCriterion("feasibility_study_postcode <>", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeGreaterThan(String value) {
			addCriterion("feasibility_study_postcode >", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeGreaterThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_postcode >=", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeLessThan(String value) {
			addCriterion("feasibility_study_postcode <", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeLessThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_postcode <=", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeLike(String value) {
			addCriterion("feasibility_study_postcode like", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeNotLike(String value) {
			addCriterion("feasibility_study_postcode not like", value,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeIn(List<String> values) {
			addCriterion("feasibility_study_postcode in", values,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeNotIn(List<String> values) {
			addCriterion("feasibility_study_postcode not in", values,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_postcode between", value1, value2,
					"feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyPostcodeNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_postcode not between", value1,
					value2, "feasibilityStudyPostcode");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressIsNull() {
			addCriterion("feasibility_study_detail_address is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressIsNotNull() {
			addCriterion("feasibility_study_detail_address is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressEqualTo(String value) {
			addCriterion("feasibility_study_detail_address =", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressNotEqualTo(String value) {
			addCriterion("feasibility_study_detail_address <>", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressGreaterThan(String value) {
			addCriterion("feasibility_study_detail_address >", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressGreaterThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_detail_address >=", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressLessThan(String value) {
			addCriterion("feasibility_study_detail_address <", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressLessThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_detail_address <=", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressLike(String value) {
			addCriterion("feasibility_study_detail_address like", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressNotLike(String value) {
			addCriterion("feasibility_study_detail_address not like", value,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressIn(List<String> values) {
			addCriterion("feasibility_study_detail_address in", values,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressNotIn(
				List<String> values) {
			addCriterion("feasibility_study_detail_address not in", values,
					"feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_detail_address between", value1,
					value2, "feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyDetailAddressNotBetween(
				String value1, String value2) {
			addCriterion("feasibility_study_detail_address not between",
					value1, value2, "feasibilityStudyDetailAddress");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlIsNull() {
			addCriterion("feasibility_study_weburl is null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlIsNotNull() {
			addCriterion("feasibility_study_weburl is not null");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlEqualTo(String value) {
			addCriterion("feasibility_study_weburl =", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlNotEqualTo(String value) {
			addCriterion("feasibility_study_weburl <>", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlGreaterThan(String value) {
			addCriterion("feasibility_study_weburl >", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlGreaterThanOrEqualTo(
				String value) {
			addCriterion("feasibility_study_weburl >=", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlLessThan(String value) {
			addCriterion("feasibility_study_weburl <", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlLessThanOrEqualTo(String value) {
			addCriterion("feasibility_study_weburl <=", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlLike(String value) {
			addCriterion("feasibility_study_weburl like", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlNotLike(String value) {
			addCriterion("feasibility_study_weburl not like", value,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlIn(List<String> values) {
			addCriterion("feasibility_study_weburl in", values,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlNotIn(List<String> values) {
			addCriterion("feasibility_study_weburl not in", values,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_weburl between", value1, value2,
					"feasibilityStudyWeburl");
			return (Criteria) this;
		}

		public Criteria andFeasibilityStudyWeburlNotBetween(String value1,
				String value2) {
			addCriterion("feasibility_study_weburl not between", value1,
					value2, "feasibilityStudyWeburl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_feasibility_study
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_feasibility_study
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 10:53:44 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}