package com.unbank.mybatis.vo;

public class BhiOwner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_owner.owner_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String ownerWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.id
	 * @return  the value of bhi_owner.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.id
	 * @param id  the value for bhi_owner.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_department
	 * @return  the value of bhi_owner.owner_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerDepartment() {
		return ownerDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_department
	 * @param ownerDepartment  the value for bhi_owner.owner_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerDepartment(String ownerDepartment) {
		this.ownerDepartment = ownerDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_people
	 * @return  the value of bhi_owner.owner_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerPeople() {
		return ownerPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_people
	 * @param ownerPeople  the value for bhi_owner.owner_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerPeople(String ownerPeople) {
		this.ownerPeople = ownerPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_people_job
	 * @return  the value of bhi_owner.owner_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerPeopleJob() {
		return ownerPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_people_job
	 * @param ownerPeopleJob  the value for bhi_owner.owner_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerPeopleJob(String ownerPeopleJob) {
		this.ownerPeopleJob = ownerPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_tel
	 * @return  the value of bhi_owner.owner_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerTel() {
		return ownerTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_tel
	 * @param ownerTel  the value for bhi_owner.owner_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerTel(String ownerTel) {
		this.ownerTel = ownerTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_fax
	 * @return  the value of bhi_owner.owner_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerFax() {
		return ownerFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_fax
	 * @param ownerFax  the value for bhi_owner.owner_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerFax(String ownerFax) {
		this.ownerFax = ownerFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_postcode
	 * @return  the value of bhi_owner.owner_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerPostcode() {
		return ownerPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_postcode
	 * @param ownerPostcode  the value for bhi_owner.owner_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerPostcode(String ownerPostcode) {
		this.ownerPostcode = ownerPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_detail_address
	 * @return  the value of bhi_owner.owner_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerDetailAddress() {
		return ownerDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_detail_address
	 * @param ownerDetailAddress  the value for bhi_owner.owner_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerDetailAddress(String ownerDetailAddress) {
		this.ownerDetailAddress = ownerDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_owner.owner_weburl
	 * @return  the value of bhi_owner.owner_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOwnerWeburl() {
		return ownerWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_owner.owner_weburl
	 * @param ownerWeburl  the value for bhi_owner.owner_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOwnerWeburl(String ownerWeburl) {
		this.ownerWeburl = ownerWeburl;
	}
}