package com.unbank.mybatis.vo;

public class BhiOther {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_other.other_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String otherWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.id
	 * @return  the value of bhi_other.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.id
	 * @param id  the value for bhi_other.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_department
	 * @return  the value of bhi_other.other_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherDepartment() {
		return otherDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_department
	 * @param otherDepartment  the value for bhi_other.other_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherDepartment(String otherDepartment) {
		this.otherDepartment = otherDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_people
	 * @return  the value of bhi_other.other_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherPeople() {
		return otherPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_people
	 * @param otherPeople  the value for bhi_other.other_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherPeople(String otherPeople) {
		this.otherPeople = otherPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_people_job
	 * @return  the value of bhi_other.other_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherPeopleJob() {
		return otherPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_people_job
	 * @param otherPeopleJob  the value for bhi_other.other_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherPeopleJob(String otherPeopleJob) {
		this.otherPeopleJob = otherPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_tel
	 * @return  the value of bhi_other.other_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherTel() {
		return otherTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_tel
	 * @param otherTel  the value for bhi_other.other_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherTel(String otherTel) {
		this.otherTel = otherTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_fax
	 * @return  the value of bhi_other.other_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherFax() {
		return otherFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_fax
	 * @param otherFax  the value for bhi_other.other_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherFax(String otherFax) {
		this.otherFax = otherFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_postcode
	 * @return  the value of bhi_other.other_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherPostcode() {
		return otherPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_postcode
	 * @param otherPostcode  the value for bhi_other.other_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherPostcode(String otherPostcode) {
		this.otherPostcode = otherPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_detail_address
	 * @return  the value of bhi_other.other_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherDetailAddress() {
		return otherDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_detail_address
	 * @param otherDetailAddress  the value for bhi_other.other_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherDetailAddress(String otherDetailAddress) {
		this.otherDetailAddress = otherDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_other.other_weburl
	 * @return  the value of bhi_other.other_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOtherWeburl() {
		return otherWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_other.other_weburl
	 * @param otherWeburl  the value for bhi_other.other_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOtherWeburl(String otherWeburl) {
		this.otherWeburl = otherWeburl;
	}
}