package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiOwnerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public BhiOwnerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentIsNull() {
			addCriterion("owner_department is null");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentIsNotNull() {
			addCriterion("owner_department is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentEqualTo(String value) {
			addCriterion("owner_department =", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentNotEqualTo(String value) {
			addCriterion("owner_department <>", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentGreaterThan(String value) {
			addCriterion("owner_department >", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("owner_department >=", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentLessThan(String value) {
			addCriterion("owner_department <", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentLessThanOrEqualTo(String value) {
			addCriterion("owner_department <=", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentLike(String value) {
			addCriterion("owner_department like", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentNotLike(String value) {
			addCriterion("owner_department not like", value, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentIn(List<String> values) {
			addCriterion("owner_department in", values, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentNotIn(List<String> values) {
			addCriterion("owner_department not in", values, "ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentBetween(String value1, String value2) {
			addCriterion("owner_department between", value1, value2,
					"ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerDepartmentNotBetween(String value1,
				String value2) {
			addCriterion("owner_department not between", value1, value2,
					"ownerDepartment");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleIsNull() {
			addCriterion("owner_people is null");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleIsNotNull() {
			addCriterion("owner_people is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleEqualTo(String value) {
			addCriterion("owner_people =", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleNotEqualTo(String value) {
			addCriterion("owner_people <>", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleGreaterThan(String value) {
			addCriterion("owner_people >", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleGreaterThanOrEqualTo(String value) {
			addCriterion("owner_people >=", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleLessThan(String value) {
			addCriterion("owner_people <", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleLessThanOrEqualTo(String value) {
			addCriterion("owner_people <=", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleLike(String value) {
			addCriterion("owner_people like", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleNotLike(String value) {
			addCriterion("owner_people not like", value, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleIn(List<String> values) {
			addCriterion("owner_people in", values, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleNotIn(List<String> values) {
			addCriterion("owner_people not in", values, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleBetween(String value1, String value2) {
			addCriterion("owner_people between", value1, value2, "ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleNotBetween(String value1, String value2) {
			addCriterion("owner_people not between", value1, value2,
					"ownerPeople");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobIsNull() {
			addCriterion("owner_people_job is null");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobIsNotNull() {
			addCriterion("owner_people_job is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobEqualTo(String value) {
			addCriterion("owner_people_job =", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobNotEqualTo(String value) {
			addCriterion("owner_people_job <>", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobGreaterThan(String value) {
			addCriterion("owner_people_job >", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobGreaterThanOrEqualTo(String value) {
			addCriterion("owner_people_job >=", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobLessThan(String value) {
			addCriterion("owner_people_job <", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobLessThanOrEqualTo(String value) {
			addCriterion("owner_people_job <=", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobLike(String value) {
			addCriterion("owner_people_job like", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobNotLike(String value) {
			addCriterion("owner_people_job not like", value, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobIn(List<String> values) {
			addCriterion("owner_people_job in", values, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobNotIn(List<String> values) {
			addCriterion("owner_people_job not in", values, "ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobBetween(String value1, String value2) {
			addCriterion("owner_people_job between", value1, value2,
					"ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerPeopleJobNotBetween(String value1, String value2) {
			addCriterion("owner_people_job not between", value1, value2,
					"ownerPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOwnerTelIsNull() {
			addCriterion("owner_tel is null");
			return (Criteria) this;
		}

		public Criteria andOwnerTelIsNotNull() {
			addCriterion("owner_tel is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerTelEqualTo(String value) {
			addCriterion("owner_tel =", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelNotEqualTo(String value) {
			addCriterion("owner_tel <>", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelGreaterThan(String value) {
			addCriterion("owner_tel >", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelGreaterThanOrEqualTo(String value) {
			addCriterion("owner_tel >=", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelLessThan(String value) {
			addCriterion("owner_tel <", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelLessThanOrEqualTo(String value) {
			addCriterion("owner_tel <=", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelLike(String value) {
			addCriterion("owner_tel like", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelNotLike(String value) {
			addCriterion("owner_tel not like", value, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelIn(List<String> values) {
			addCriterion("owner_tel in", values, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelNotIn(List<String> values) {
			addCriterion("owner_tel not in", values, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelBetween(String value1, String value2) {
			addCriterion("owner_tel between", value1, value2, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerTelNotBetween(String value1, String value2) {
			addCriterion("owner_tel not between", value1, value2, "ownerTel");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxIsNull() {
			addCriterion("owner_fax is null");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxIsNotNull() {
			addCriterion("owner_fax is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxEqualTo(String value) {
			addCriterion("owner_fax =", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxNotEqualTo(String value) {
			addCriterion("owner_fax <>", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxGreaterThan(String value) {
			addCriterion("owner_fax >", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxGreaterThanOrEqualTo(String value) {
			addCriterion("owner_fax >=", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxLessThan(String value) {
			addCriterion("owner_fax <", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxLessThanOrEqualTo(String value) {
			addCriterion("owner_fax <=", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxLike(String value) {
			addCriterion("owner_fax like", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxNotLike(String value) {
			addCriterion("owner_fax not like", value, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxIn(List<String> values) {
			addCriterion("owner_fax in", values, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxNotIn(List<String> values) {
			addCriterion("owner_fax not in", values, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxBetween(String value1, String value2) {
			addCriterion("owner_fax between", value1, value2, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerFaxNotBetween(String value1, String value2) {
			addCriterion("owner_fax not between", value1, value2, "ownerFax");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeIsNull() {
			addCriterion("owner_postcode is null");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeIsNotNull() {
			addCriterion("owner_postcode is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeEqualTo(String value) {
			addCriterion("owner_postcode =", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeNotEqualTo(String value) {
			addCriterion("owner_postcode <>", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeGreaterThan(String value) {
			addCriterion("owner_postcode >", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeGreaterThanOrEqualTo(String value) {
			addCriterion("owner_postcode >=", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeLessThan(String value) {
			addCriterion("owner_postcode <", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeLessThanOrEqualTo(String value) {
			addCriterion("owner_postcode <=", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeLike(String value) {
			addCriterion("owner_postcode like", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeNotLike(String value) {
			addCriterion("owner_postcode not like", value, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeIn(List<String> values) {
			addCriterion("owner_postcode in", values, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeNotIn(List<String> values) {
			addCriterion("owner_postcode not in", values, "ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeBetween(String value1, String value2) {
			addCriterion("owner_postcode between", value1, value2,
					"ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerPostcodeNotBetween(String value1, String value2) {
			addCriterion("owner_postcode not between", value1, value2,
					"ownerPostcode");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressIsNull() {
			addCriterion("owner_detail_address is null");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressIsNotNull() {
			addCriterion("owner_detail_address is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressEqualTo(String value) {
			addCriterion("owner_detail_address =", value, "ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressNotEqualTo(String value) {
			addCriterion("owner_detail_address <>", value, "ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressGreaterThan(String value) {
			addCriterion("owner_detail_address >", value, "ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("owner_detail_address >=", value, "ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressLessThan(String value) {
			addCriterion("owner_detail_address <", value, "ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressLessThanOrEqualTo(String value) {
			addCriterion("owner_detail_address <=", value, "ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressLike(String value) {
			addCriterion("owner_detail_address like", value,
					"ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressNotLike(String value) {
			addCriterion("owner_detail_address not like", value,
					"ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressIn(List<String> values) {
			addCriterion("owner_detail_address in", values,
					"ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressNotIn(List<String> values) {
			addCriterion("owner_detail_address not in", values,
					"ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressBetween(String value1,
				String value2) {
			addCriterion("owner_detail_address between", value1, value2,
					"ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerDetailAddressNotBetween(String value1,
				String value2) {
			addCriterion("owner_detail_address not between", value1, value2,
					"ownerDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlIsNull() {
			addCriterion("owner_weburl is null");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlIsNotNull() {
			addCriterion("owner_weburl is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlEqualTo(String value) {
			addCriterion("owner_weburl =", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlNotEqualTo(String value) {
			addCriterion("owner_weburl <>", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlGreaterThan(String value) {
			addCriterion("owner_weburl >", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlGreaterThanOrEqualTo(String value) {
			addCriterion("owner_weburl >=", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlLessThan(String value) {
			addCriterion("owner_weburl <", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlLessThanOrEqualTo(String value) {
			addCriterion("owner_weburl <=", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlLike(String value) {
			addCriterion("owner_weburl like", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlNotLike(String value) {
			addCriterion("owner_weburl not like", value, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlIn(List<String> values) {
			addCriterion("owner_weburl in", values, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlNotIn(List<String> values) {
			addCriterion("owner_weburl not in", values, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlBetween(String value1, String value2) {
			addCriterion("owner_weburl between", value1, value2, "ownerWeburl");
			return (Criteria) this;
		}

		public Criteria andOwnerWeburlNotBetween(String value1, String value2) {
			addCriterion("owner_weburl not between", value1, value2,
					"ownerWeburl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_owner
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 10:53:44 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}