package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiOtherExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public BhiOtherExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentIsNull() {
			addCriterion("other_department is null");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentIsNotNull() {
			addCriterion("other_department is not null");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentEqualTo(String value) {
			addCriterion("other_department =", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentNotEqualTo(String value) {
			addCriterion("other_department <>", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentGreaterThan(String value) {
			addCriterion("other_department >", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("other_department >=", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentLessThan(String value) {
			addCriterion("other_department <", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentLessThanOrEqualTo(String value) {
			addCriterion("other_department <=", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentLike(String value) {
			addCriterion("other_department like", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentNotLike(String value) {
			addCriterion("other_department not like", value, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentIn(List<String> values) {
			addCriterion("other_department in", values, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentNotIn(List<String> values) {
			addCriterion("other_department not in", values, "otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentBetween(String value1, String value2) {
			addCriterion("other_department between", value1, value2,
					"otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherDepartmentNotBetween(String value1,
				String value2) {
			addCriterion("other_department not between", value1, value2,
					"otherDepartment");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleIsNull() {
			addCriterion("other_people is null");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleIsNotNull() {
			addCriterion("other_people is not null");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleEqualTo(String value) {
			addCriterion("other_people =", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleNotEqualTo(String value) {
			addCriterion("other_people <>", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleGreaterThan(String value) {
			addCriterion("other_people >", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleGreaterThanOrEqualTo(String value) {
			addCriterion("other_people >=", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleLessThan(String value) {
			addCriterion("other_people <", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleLessThanOrEqualTo(String value) {
			addCriterion("other_people <=", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleLike(String value) {
			addCriterion("other_people like", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleNotLike(String value) {
			addCriterion("other_people not like", value, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleIn(List<String> values) {
			addCriterion("other_people in", values, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleNotIn(List<String> values) {
			addCriterion("other_people not in", values, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleBetween(String value1, String value2) {
			addCriterion("other_people between", value1, value2, "otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleNotBetween(String value1, String value2) {
			addCriterion("other_people not between", value1, value2,
					"otherPeople");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobIsNull() {
			addCriterion("other_people_job is null");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobIsNotNull() {
			addCriterion("other_people_job is not null");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobEqualTo(String value) {
			addCriterion("other_people_job =", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobNotEqualTo(String value) {
			addCriterion("other_people_job <>", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobGreaterThan(String value) {
			addCriterion("other_people_job >", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobGreaterThanOrEqualTo(String value) {
			addCriterion("other_people_job >=", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobLessThan(String value) {
			addCriterion("other_people_job <", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobLessThanOrEqualTo(String value) {
			addCriterion("other_people_job <=", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobLike(String value) {
			addCriterion("other_people_job like", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobNotLike(String value) {
			addCriterion("other_people_job not like", value, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobIn(List<String> values) {
			addCriterion("other_people_job in", values, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobNotIn(List<String> values) {
			addCriterion("other_people_job not in", values, "otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobBetween(String value1, String value2) {
			addCriterion("other_people_job between", value1, value2,
					"otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherPeopleJobNotBetween(String value1, String value2) {
			addCriterion("other_people_job not between", value1, value2,
					"otherPeopleJob");
			return (Criteria) this;
		}

		public Criteria andOtherTelIsNull() {
			addCriterion("other_tel is null");
			return (Criteria) this;
		}

		public Criteria andOtherTelIsNotNull() {
			addCriterion("other_tel is not null");
			return (Criteria) this;
		}

		public Criteria andOtherTelEqualTo(String value) {
			addCriterion("other_tel =", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelNotEqualTo(String value) {
			addCriterion("other_tel <>", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelGreaterThan(String value) {
			addCriterion("other_tel >", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelGreaterThanOrEqualTo(String value) {
			addCriterion("other_tel >=", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelLessThan(String value) {
			addCriterion("other_tel <", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelLessThanOrEqualTo(String value) {
			addCriterion("other_tel <=", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelLike(String value) {
			addCriterion("other_tel like", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelNotLike(String value) {
			addCriterion("other_tel not like", value, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelIn(List<String> values) {
			addCriterion("other_tel in", values, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelNotIn(List<String> values) {
			addCriterion("other_tel not in", values, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelBetween(String value1, String value2) {
			addCriterion("other_tel between", value1, value2, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherTelNotBetween(String value1, String value2) {
			addCriterion("other_tel not between", value1, value2, "otherTel");
			return (Criteria) this;
		}

		public Criteria andOtherFaxIsNull() {
			addCriterion("other_fax is null");
			return (Criteria) this;
		}

		public Criteria andOtherFaxIsNotNull() {
			addCriterion("other_fax is not null");
			return (Criteria) this;
		}

		public Criteria andOtherFaxEqualTo(String value) {
			addCriterion("other_fax =", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxNotEqualTo(String value) {
			addCriterion("other_fax <>", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxGreaterThan(String value) {
			addCriterion("other_fax >", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxGreaterThanOrEqualTo(String value) {
			addCriterion("other_fax >=", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxLessThan(String value) {
			addCriterion("other_fax <", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxLessThanOrEqualTo(String value) {
			addCriterion("other_fax <=", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxLike(String value) {
			addCriterion("other_fax like", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxNotLike(String value) {
			addCriterion("other_fax not like", value, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxIn(List<String> values) {
			addCriterion("other_fax in", values, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxNotIn(List<String> values) {
			addCriterion("other_fax not in", values, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxBetween(String value1, String value2) {
			addCriterion("other_fax between", value1, value2, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherFaxNotBetween(String value1, String value2) {
			addCriterion("other_fax not between", value1, value2, "otherFax");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeIsNull() {
			addCriterion("other_postcode is null");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeIsNotNull() {
			addCriterion("other_postcode is not null");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeEqualTo(String value) {
			addCriterion("other_postcode =", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeNotEqualTo(String value) {
			addCriterion("other_postcode <>", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeGreaterThan(String value) {
			addCriterion("other_postcode >", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeGreaterThanOrEqualTo(String value) {
			addCriterion("other_postcode >=", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeLessThan(String value) {
			addCriterion("other_postcode <", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeLessThanOrEqualTo(String value) {
			addCriterion("other_postcode <=", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeLike(String value) {
			addCriterion("other_postcode like", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeNotLike(String value) {
			addCriterion("other_postcode not like", value, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeIn(List<String> values) {
			addCriterion("other_postcode in", values, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeNotIn(List<String> values) {
			addCriterion("other_postcode not in", values, "otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeBetween(String value1, String value2) {
			addCriterion("other_postcode between", value1, value2,
					"otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherPostcodeNotBetween(String value1, String value2) {
			addCriterion("other_postcode not between", value1, value2,
					"otherPostcode");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressIsNull() {
			addCriterion("other_detail_address is null");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressIsNotNull() {
			addCriterion("other_detail_address is not null");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressEqualTo(String value) {
			addCriterion("other_detail_address =", value, "otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressNotEqualTo(String value) {
			addCriterion("other_detail_address <>", value, "otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressGreaterThan(String value) {
			addCriterion("other_detail_address >", value, "otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("other_detail_address >=", value, "otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressLessThan(String value) {
			addCriterion("other_detail_address <", value, "otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressLessThanOrEqualTo(String value) {
			addCriterion("other_detail_address <=", value, "otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressLike(String value) {
			addCriterion("other_detail_address like", value,
					"otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressNotLike(String value) {
			addCriterion("other_detail_address not like", value,
					"otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressIn(List<String> values) {
			addCriterion("other_detail_address in", values,
					"otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressNotIn(List<String> values) {
			addCriterion("other_detail_address not in", values,
					"otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressBetween(String value1,
				String value2) {
			addCriterion("other_detail_address between", value1, value2,
					"otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherDetailAddressNotBetween(String value1,
				String value2) {
			addCriterion("other_detail_address not between", value1, value2,
					"otherDetailAddress");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlIsNull() {
			addCriterion("other_weburl is null");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlIsNotNull() {
			addCriterion("other_weburl is not null");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlEqualTo(String value) {
			addCriterion("other_weburl =", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlNotEqualTo(String value) {
			addCriterion("other_weburl <>", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlGreaterThan(String value) {
			addCriterion("other_weburl >", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlGreaterThanOrEqualTo(String value) {
			addCriterion("other_weburl >=", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlLessThan(String value) {
			addCriterion("other_weburl <", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlLessThanOrEqualTo(String value) {
			addCriterion("other_weburl <=", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlLike(String value) {
			addCriterion("other_weburl like", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlNotLike(String value) {
			addCriterion("other_weburl not like", value, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlIn(List<String> values) {
			addCriterion("other_weburl in", values, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlNotIn(List<String> values) {
			addCriterion("other_weburl not in", values, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlBetween(String value1, String value2) {
			addCriterion("other_weburl between", value1, value2, "otherWeburl");
			return (Criteria) this;
		}

		public Criteria andOtherWeburlNotBetween(String value1, String value2) {
			addCriterion("other_weburl not between", value1, value2,
					"otherWeburl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_other
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 10:53:44 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}