package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiPrimaryDesignExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public BhiPrimaryDesignExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentIsNull() {
			addCriterion("primary_design_department is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentIsNotNull() {
			addCriterion("primary_design_department is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentEqualTo(String value) {
			addCriterion("primary_design_department =", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentNotEqualTo(String value) {
			addCriterion("primary_design_department <>", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentGreaterThan(String value) {
			addCriterion("primary_design_department >", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentGreaterThanOrEqualTo(
				String value) {
			addCriterion("primary_design_department >=", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentLessThan(String value) {
			addCriterion("primary_design_department <", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentLessThanOrEqualTo(String value) {
			addCriterion("primary_design_department <=", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentLike(String value) {
			addCriterion("primary_design_department like", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentNotLike(String value) {
			addCriterion("primary_design_department not like", value,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentIn(List<String> values) {
			addCriterion("primary_design_department in", values,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentNotIn(List<String> values) {
			addCriterion("primary_design_department not in", values,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentBetween(String value1,
				String value2) {
			addCriterion("primary_design_department between", value1, value2,
					"primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDepartmentNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_department not between", value1,
					value2, "primaryDesignDepartment");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleIsNull() {
			addCriterion("primary_design_people is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleIsNotNull() {
			addCriterion("primary_design_people is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleEqualTo(String value) {
			addCriterion("primary_design_people =", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleNotEqualTo(String value) {
			addCriterion("primary_design_people <>", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleGreaterThan(String value) {
			addCriterion("primary_design_people >", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleGreaterThanOrEqualTo(String value) {
			addCriterion("primary_design_people >=", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleLessThan(String value) {
			addCriterion("primary_design_people <", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleLessThanOrEqualTo(String value) {
			addCriterion("primary_design_people <=", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleLike(String value) {
			addCriterion("primary_design_people like", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleNotLike(String value) {
			addCriterion("primary_design_people not like", value,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleIn(List<String> values) {
			addCriterion("primary_design_people in", values,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleNotIn(List<String> values) {
			addCriterion("primary_design_people not in", values,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleBetween(String value1,
				String value2) {
			addCriterion("primary_design_people between", value1, value2,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_people not between", value1, value2,
					"primaryDesignPeople");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobIsNull() {
			addCriterion("primary_design_people_job is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobIsNotNull() {
			addCriterion("primary_design_people_job is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobEqualTo(String value) {
			addCriterion("primary_design_people_job =", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobNotEqualTo(String value) {
			addCriterion("primary_design_people_job <>", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobGreaterThan(String value) {
			addCriterion("primary_design_people_job >", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobGreaterThanOrEqualTo(
				String value) {
			addCriterion("primary_design_people_job >=", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobLessThan(String value) {
			addCriterion("primary_design_people_job <", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobLessThanOrEqualTo(String value) {
			addCriterion("primary_design_people_job <=", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobLike(String value) {
			addCriterion("primary_design_people_job like", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobNotLike(String value) {
			addCriterion("primary_design_people_job not like", value,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobIn(List<String> values) {
			addCriterion("primary_design_people_job in", values,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobNotIn(List<String> values) {
			addCriterion("primary_design_people_job not in", values,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobBetween(String value1,
				String value2) {
			addCriterion("primary_design_people_job between", value1, value2,
					"primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPeopleJobNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_people_job not between", value1,
					value2, "primaryDesignPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelIsNull() {
			addCriterion("primary_design_tel is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelIsNotNull() {
			addCriterion("primary_design_tel is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelEqualTo(String value) {
			addCriterion("primary_design_tel =", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelNotEqualTo(String value) {
			addCriterion("primary_design_tel <>", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelGreaterThan(String value) {
			addCriterion("primary_design_tel >", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelGreaterThanOrEqualTo(String value) {
			addCriterion("primary_design_tel >=", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelLessThan(String value) {
			addCriterion("primary_design_tel <", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelLessThanOrEqualTo(String value) {
			addCriterion("primary_design_tel <=", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelLike(String value) {
			addCriterion("primary_design_tel like", value, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelNotLike(String value) {
			addCriterion("primary_design_tel not like", value,
					"primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelIn(List<String> values) {
			addCriterion("primary_design_tel in", values, "primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelNotIn(List<String> values) {
			addCriterion("primary_design_tel not in", values,
					"primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelBetween(String value1, String value2) {
			addCriterion("primary_design_tel between", value1, value2,
					"primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignTelNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_tel not between", value1, value2,
					"primaryDesignTel");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxIsNull() {
			addCriterion("primary_design_fax is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxIsNotNull() {
			addCriterion("primary_design_fax is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxEqualTo(String value) {
			addCriterion("primary_design_fax =", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxNotEqualTo(String value) {
			addCriterion("primary_design_fax <>", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxGreaterThan(String value) {
			addCriterion("primary_design_fax >", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxGreaterThanOrEqualTo(String value) {
			addCriterion("primary_design_fax >=", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxLessThan(String value) {
			addCriterion("primary_design_fax <", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxLessThanOrEqualTo(String value) {
			addCriterion("primary_design_fax <=", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxLike(String value) {
			addCriterion("primary_design_fax like", value, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxNotLike(String value) {
			addCriterion("primary_design_fax not like", value,
					"primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxIn(List<String> values) {
			addCriterion("primary_design_fax in", values, "primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxNotIn(List<String> values) {
			addCriterion("primary_design_fax not in", values,
					"primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxBetween(String value1, String value2) {
			addCriterion("primary_design_fax between", value1, value2,
					"primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignFaxNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_fax not between", value1, value2,
					"primaryDesignFax");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeIsNull() {
			addCriterion("primary_design_postcode is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeIsNotNull() {
			addCriterion("primary_design_postcode is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeEqualTo(String value) {
			addCriterion("primary_design_postcode =", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeNotEqualTo(String value) {
			addCriterion("primary_design_postcode <>", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeGreaterThan(String value) {
			addCriterion("primary_design_postcode >", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeGreaterThanOrEqualTo(
				String value) {
			addCriterion("primary_design_postcode >=", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeLessThan(String value) {
			addCriterion("primary_design_postcode <", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeLessThanOrEqualTo(String value) {
			addCriterion("primary_design_postcode <=", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeLike(String value) {
			addCriterion("primary_design_postcode like", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeNotLike(String value) {
			addCriterion("primary_design_postcode not like", value,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeIn(List<String> values) {
			addCriterion("primary_design_postcode in", values,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeNotIn(List<String> values) {
			addCriterion("primary_design_postcode not in", values,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeBetween(String value1,
				String value2) {
			addCriterion("primary_design_postcode between", value1, value2,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignPostcodeNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_postcode not between", value1, value2,
					"primaryDesignPostcode");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressIsNull() {
			addCriterion("primary_design_detail_address is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressIsNotNull() {
			addCriterion("primary_design_detail_address is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressEqualTo(String value) {
			addCriterion("primary_design_detail_address =", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressNotEqualTo(String value) {
			addCriterion("primary_design_detail_address <>", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressGreaterThan(String value) {
			addCriterion("primary_design_detail_address >", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressGreaterThanOrEqualTo(
				String value) {
			addCriterion("primary_design_detail_address >=", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressLessThan(String value) {
			addCriterion("primary_design_detail_address <", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressLessThanOrEqualTo(
				String value) {
			addCriterion("primary_design_detail_address <=", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressLike(String value) {
			addCriterion("primary_design_detail_address like", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressNotLike(String value) {
			addCriterion("primary_design_detail_address not like", value,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressIn(List<String> values) {
			addCriterion("primary_design_detail_address in", values,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressNotIn(List<String> values) {
			addCriterion("primary_design_detail_address not in", values,
					"primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressBetween(String value1,
				String value2) {
			addCriterion("primary_design_detail_address between", value1,
					value2, "primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignDetailAddressNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_detail_address not between", value1,
					value2, "primaryDesignDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlIsNull() {
			addCriterion("primary_design_weburl is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlIsNotNull() {
			addCriterion("primary_design_weburl is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlEqualTo(String value) {
			addCriterion("primary_design_weburl =", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlNotEqualTo(String value) {
			addCriterion("primary_design_weburl <>", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlGreaterThan(String value) {
			addCriterion("primary_design_weburl >", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlGreaterThanOrEqualTo(String value) {
			addCriterion("primary_design_weburl >=", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlLessThan(String value) {
			addCriterion("primary_design_weburl <", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlLessThanOrEqualTo(String value) {
			addCriterion("primary_design_weburl <=", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlLike(String value) {
			addCriterion("primary_design_weburl like", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlNotLike(String value) {
			addCriterion("primary_design_weburl not like", value,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlIn(List<String> values) {
			addCriterion("primary_design_weburl in", values,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlNotIn(List<String> values) {
			addCriterion("primary_design_weburl not in", values,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlBetween(String value1,
				String value2) {
			addCriterion("primary_design_weburl between", value1, value2,
					"primaryDesignWeburl");
			return (Criteria) this;
		}

		public Criteria andPrimaryDesignWeburlNotBetween(String value1,
				String value2) {
			addCriterion("primary_design_weburl not between", value1, value2,
					"primaryDesignWeburl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_primary_design
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 10:53:44 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}