package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.List;

public class BhiPlantExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public BhiPlantExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentIsNull() {
			addCriterion("plant_department is null");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentIsNotNull() {
			addCriterion("plant_department is not null");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentEqualTo(String value) {
			addCriterion("plant_department =", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentNotEqualTo(String value) {
			addCriterion("plant_department <>", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentGreaterThan(String value) {
			addCriterion("plant_department >", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("plant_department >=", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentLessThan(String value) {
			addCriterion("plant_department <", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentLessThanOrEqualTo(String value) {
			addCriterion("plant_department <=", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentLike(String value) {
			addCriterion("plant_department like", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentNotLike(String value) {
			addCriterion("plant_department not like", value, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentIn(List<String> values) {
			addCriterion("plant_department in", values, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentNotIn(List<String> values) {
			addCriterion("plant_department not in", values, "plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentBetween(String value1, String value2) {
			addCriterion("plant_department between", value1, value2,
					"plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantDepartmentNotBetween(String value1,
				String value2) {
			addCriterion("plant_department not between", value1, value2,
					"plantDepartment");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleIsNull() {
			addCriterion("plant_people is null");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleIsNotNull() {
			addCriterion("plant_people is not null");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleEqualTo(String value) {
			addCriterion("plant_people =", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleNotEqualTo(String value) {
			addCriterion("plant_people <>", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleGreaterThan(String value) {
			addCriterion("plant_people >", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleGreaterThanOrEqualTo(String value) {
			addCriterion("plant_people >=", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleLessThan(String value) {
			addCriterion("plant_people <", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleLessThanOrEqualTo(String value) {
			addCriterion("plant_people <=", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleLike(String value) {
			addCriterion("plant_people like", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleNotLike(String value) {
			addCriterion("plant_people not like", value, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleIn(List<String> values) {
			addCriterion("plant_people in", values, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleNotIn(List<String> values) {
			addCriterion("plant_people not in", values, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleBetween(String value1, String value2) {
			addCriterion("plant_people between", value1, value2, "plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleNotBetween(String value1, String value2) {
			addCriterion("plant_people not between", value1, value2,
					"plantPeople");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobIsNull() {
			addCriterion("plant_people_job is null");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobIsNotNull() {
			addCriterion("plant_people_job is not null");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobEqualTo(String value) {
			addCriterion("plant_people_job =", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobNotEqualTo(String value) {
			addCriterion("plant_people_job <>", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobGreaterThan(String value) {
			addCriterion("plant_people_job >", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobGreaterThanOrEqualTo(String value) {
			addCriterion("plant_people_job >=", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobLessThan(String value) {
			addCriterion("plant_people_job <", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobLessThanOrEqualTo(String value) {
			addCriterion("plant_people_job <=", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobLike(String value) {
			addCriterion("plant_people_job like", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobNotLike(String value) {
			addCriterion("plant_people_job not like", value, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobIn(List<String> values) {
			addCriterion("plant_people_job in", values, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobNotIn(List<String> values) {
			addCriterion("plant_people_job not in", values, "plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobBetween(String value1, String value2) {
			addCriterion("plant_people_job between", value1, value2,
					"plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantPeopleJobNotBetween(String value1, String value2) {
			addCriterion("plant_people_job not between", value1, value2,
					"plantPeopleJob");
			return (Criteria) this;
		}

		public Criteria andPlantTelIsNull() {
			addCriterion("plant_tel is null");
			return (Criteria) this;
		}

		public Criteria andPlantTelIsNotNull() {
			addCriterion("plant_tel is not null");
			return (Criteria) this;
		}

		public Criteria andPlantTelEqualTo(String value) {
			addCriterion("plant_tel =", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelNotEqualTo(String value) {
			addCriterion("plant_tel <>", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelGreaterThan(String value) {
			addCriterion("plant_tel >", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelGreaterThanOrEqualTo(String value) {
			addCriterion("plant_tel >=", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelLessThan(String value) {
			addCriterion("plant_tel <", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelLessThanOrEqualTo(String value) {
			addCriterion("plant_tel <=", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelLike(String value) {
			addCriterion("plant_tel like", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelNotLike(String value) {
			addCriterion("plant_tel not like", value, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelIn(List<String> values) {
			addCriterion("plant_tel in", values, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelNotIn(List<String> values) {
			addCriterion("plant_tel not in", values, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelBetween(String value1, String value2) {
			addCriterion("plant_tel between", value1, value2, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantTelNotBetween(String value1, String value2) {
			addCriterion("plant_tel not between", value1, value2, "plantTel");
			return (Criteria) this;
		}

		public Criteria andPlantFaxIsNull() {
			addCriterion("plant_fax is null");
			return (Criteria) this;
		}

		public Criteria andPlantFaxIsNotNull() {
			addCriterion("plant_fax is not null");
			return (Criteria) this;
		}

		public Criteria andPlantFaxEqualTo(String value) {
			addCriterion("plant_fax =", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxNotEqualTo(String value) {
			addCriterion("plant_fax <>", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxGreaterThan(String value) {
			addCriterion("plant_fax >", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxGreaterThanOrEqualTo(String value) {
			addCriterion("plant_fax >=", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxLessThan(String value) {
			addCriterion("plant_fax <", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxLessThanOrEqualTo(String value) {
			addCriterion("plant_fax <=", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxLike(String value) {
			addCriterion("plant_fax like", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxNotLike(String value) {
			addCriterion("plant_fax not like", value, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxIn(List<String> values) {
			addCriterion("plant_fax in", values, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxNotIn(List<String> values) {
			addCriterion("plant_fax not in", values, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxBetween(String value1, String value2) {
			addCriterion("plant_fax between", value1, value2, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantFaxNotBetween(String value1, String value2) {
			addCriterion("plant_fax not between", value1, value2, "plantFax");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeIsNull() {
			addCriterion("plant_postcode is null");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeIsNotNull() {
			addCriterion("plant_postcode is not null");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeEqualTo(String value) {
			addCriterion("plant_postcode =", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeNotEqualTo(String value) {
			addCriterion("plant_postcode <>", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeGreaterThan(String value) {
			addCriterion("plant_postcode >", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeGreaterThanOrEqualTo(String value) {
			addCriterion("plant_postcode >=", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeLessThan(String value) {
			addCriterion("plant_postcode <", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeLessThanOrEqualTo(String value) {
			addCriterion("plant_postcode <=", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeLike(String value) {
			addCriterion("plant_postcode like", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeNotLike(String value) {
			addCriterion("plant_postcode not like", value, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeIn(List<String> values) {
			addCriterion("plant_postcode in", values, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeNotIn(List<String> values) {
			addCriterion("plant_postcode not in", values, "plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeBetween(String value1, String value2) {
			addCriterion("plant_postcode between", value1, value2,
					"plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantPostcodeNotBetween(String value1, String value2) {
			addCriterion("plant_postcode not between", value1, value2,
					"plantPostcode");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressIsNull() {
			addCriterion("plant_detail_address is null");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressIsNotNull() {
			addCriterion("plant_detail_address is not null");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressEqualTo(String value) {
			addCriterion("plant_detail_address =", value, "plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressNotEqualTo(String value) {
			addCriterion("plant_detail_address <>", value, "plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressGreaterThan(String value) {
			addCriterion("plant_detail_address >", value, "plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("plant_detail_address >=", value, "plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressLessThan(String value) {
			addCriterion("plant_detail_address <", value, "plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressLessThanOrEqualTo(String value) {
			addCriterion("plant_detail_address <=", value, "plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressLike(String value) {
			addCriterion("plant_detail_address like", value,
					"plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressNotLike(String value) {
			addCriterion("plant_detail_address not like", value,
					"plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressIn(List<String> values) {
			addCriterion("plant_detail_address in", values,
					"plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressNotIn(List<String> values) {
			addCriterion("plant_detail_address not in", values,
					"plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressBetween(String value1,
				String value2) {
			addCriterion("plant_detail_address between", value1, value2,
					"plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantDetailAddressNotBetween(String value1,
				String value2) {
			addCriterion("plant_detail_address not between", value1, value2,
					"plantDetailAddress");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlIsNull() {
			addCriterion("plant_weburl is null");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlIsNotNull() {
			addCriterion("plant_weburl is not null");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlEqualTo(String value) {
			addCriterion("plant_weburl =", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlNotEqualTo(String value) {
			addCriterion("plant_weburl <>", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlGreaterThan(String value) {
			addCriterion("plant_weburl >", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlGreaterThanOrEqualTo(String value) {
			addCriterion("plant_weburl >=", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlLessThan(String value) {
			addCriterion("plant_weburl <", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlLessThanOrEqualTo(String value) {
			addCriterion("plant_weburl <=", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlLike(String value) {
			addCriterion("plant_weburl like", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlNotLike(String value) {
			addCriterion("plant_weburl not like", value, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlIn(List<String> values) {
			addCriterion("plant_weburl in", values, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlNotIn(List<String> values) {
			addCriterion("plant_weburl not in", values, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlBetween(String value1, String value2) {
			addCriterion("plant_weburl between", value1, value2, "plantWeburl");
			return (Criteria) this;
		}

		public Criteria andPlantWeburlNotBetween(String value1, String value2) {
			addCriterion("plant_weburl not between", value1, value2,
					"plantWeburl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_plant
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 31 10:53:44 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}