package com.unbank.mybatis.vo;

public class BhiProWithBLOBs extends BhiPro {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_content
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_intro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proIntro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_content
	 * @return  the value of bhi_pro.pro_content
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProContent() {
		return proContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_content
	 * @param proContent  the value for bhi_pro.pro_content
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProContent(String proContent) {
		this.proContent = proContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_intro
	 * @return  the value of bhi_pro.pro_intro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProIntro() {
		return proIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_intro
	 * @param proIntro  the value for bhi_pro.pro_intro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProIntro(String proIntro) {
		this.proIntro = proIntro;
	}
}