package com.unbank.mybatis.vo;

public class BhiProDataWithBLOBs extends BhiProData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_content
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_intro
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_content
     *
     * @return the value of bhi_pro_data.pro_content
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProContent() {
        return proContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_content
     *
     * @param proContent the value for bhi_pro_data.pro_content
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProContent(String proContent) {
        this.proContent = proContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_intro
     *
     * @return the value of bhi_pro_data.pro_intro
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProIntro() {
        return proIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_intro
     *
     * @param proIntro the value for bhi_pro_data.pro_intro
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProIntro(String proIntro) {
        this.proIntro = proIntro;
    }
}