package com.unbank.mybatis.vo;

import java.util.Date;

public class BhiProData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.id
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_name
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_area
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_time
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private Date proTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_nature
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.firm_nature
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String firmNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_trade
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_assets
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_stage
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_way
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_office
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_cycle
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_fund
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.equipment_source
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String equipmentSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.governing_unit
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String governingUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.address
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_facility
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proFacility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.weburl
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String weburl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.type
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_datavalue
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proDatavalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_pro_data.pro_dataunit
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    private String proDataunit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.id
     *
     * @return the value of bhi_pro_data.id
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.id
     *
     * @param id the value for bhi_pro_data.id
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_name
     *
     * @return the value of bhi_pro_data.pro_name
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_name
     *
     * @param proName the value for bhi_pro_data.pro_name
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_area
     *
     * @return the value of bhi_pro_data.pro_area
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProArea() {
        return proArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_area
     *
     * @param proArea the value for bhi_pro_data.pro_area
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProArea(String proArea) {
        this.proArea = proArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_time
     *
     * @return the value of bhi_pro_data.pro_time
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public Date getProTime() {
        return proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_time
     *
     * @param proTime the value for bhi_pro_data.pro_time
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProTime(Date proTime) {
        this.proTime = proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_nature
     *
     * @return the value of bhi_pro_data.pro_nature
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProNature() {
        return proNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_nature
     *
     * @param proNature the value for bhi_pro_data.pro_nature
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProNature(String proNature) {
        this.proNature = proNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.firm_nature
     *
     * @return the value of bhi_pro_data.firm_nature
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getFirmNature() {
        return firmNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.firm_nature
     *
     * @param firmNature the value for bhi_pro_data.firm_nature
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setFirmNature(String firmNature) {
        this.firmNature = firmNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_trade
     *
     * @return the value of bhi_pro_data.pro_trade
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProTrade() {
        return proTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_trade
     *
     * @param proTrade the value for bhi_pro_data.pro_trade
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProTrade(String proTrade) {
        this.proTrade = proTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_assets
     *
     * @return the value of bhi_pro_data.pro_assets
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProAssets() {
        return proAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_assets
     *
     * @param proAssets the value for bhi_pro_data.pro_assets
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProAssets(String proAssets) {
        this.proAssets = proAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_stage
     *
     * @return the value of bhi_pro_data.pro_stage
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProStage() {
        return proStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_stage
     *
     * @param proStage the value for bhi_pro_data.pro_stage
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProStage(String proStage) {
        this.proStage = proStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_way
     *
     * @return the value of bhi_pro_data.pro_way
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProWay() {
        return proWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_way
     *
     * @param proWay the value for bhi_pro_data.pro_way
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProWay(String proWay) {
        this.proWay = proWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_office
     *
     * @return the value of bhi_pro_data.pro_office
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProOffice() {
        return proOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_office
     *
     * @param proOffice the value for bhi_pro_data.pro_office
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProOffice(String proOffice) {
        this.proOffice = proOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_cycle
     *
     * @return the value of bhi_pro_data.pro_cycle
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProCycle() {
        return proCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_cycle
     *
     * @param proCycle the value for bhi_pro_data.pro_cycle
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProCycle(String proCycle) {
        this.proCycle = proCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_fund
     *
     * @return the value of bhi_pro_data.pro_fund
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProFund() {
        return proFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_fund
     *
     * @param proFund the value for bhi_pro_data.pro_fund
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProFund(String proFund) {
        this.proFund = proFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.equipment_source
     *
     * @return the value of bhi_pro_data.equipment_source
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getEquipmentSource() {
        return equipmentSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.equipment_source
     *
     * @param equipmentSource the value for bhi_pro_data.equipment_source
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setEquipmentSource(String equipmentSource) {
        this.equipmentSource = equipmentSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.governing_unit
     *
     * @return the value of bhi_pro_data.governing_unit
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getGoverningUnit() {
        return governingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.governing_unit
     *
     * @param governingUnit the value for bhi_pro_data.governing_unit
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setGoverningUnit(String governingUnit) {
        this.governingUnit = governingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.address
     *
     * @return the value of bhi_pro_data.address
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.address
     *
     * @param address the value for bhi_pro_data.address
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_facility
     *
     * @return the value of bhi_pro_data.pro_facility
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProFacility() {
        return proFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_facility
     *
     * @param proFacility the value for bhi_pro_data.pro_facility
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProFacility(String proFacility) {
        this.proFacility = proFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.weburl
     *
     * @return the value of bhi_pro_data.weburl
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getWeburl() {
        return weburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.weburl
     *
     * @param weburl the value for bhi_pro_data.weburl
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setWeburl(String weburl) {
        this.weburl = weburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.type
     *
     * @return the value of bhi_pro_data.type
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.type
     *
     * @param type the value for bhi_pro_data.type
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_datavalue
     *
     * @return the value of bhi_pro_data.pro_datavalue
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProDatavalue() {
        return proDatavalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_datavalue
     *
     * @param proDatavalue the value for bhi_pro_data.pro_datavalue
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProDatavalue(String proDatavalue) {
        this.proDatavalue = proDatavalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_pro_data.pro_dataunit
     *
     * @return the value of bhi_pro_data.pro_dataunit
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public String getProDataunit() {
        return proDataunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_pro_data.pro_dataunit
     *
     * @param proDataunit the value for bhi_pro_data.pro_dataunit
     *
     * @mbggenerated Thu Jul 07 09:45:46 GMT+08:00 2016
     */
    public void setProDataunit(String proDataunit) {
        this.proDataunit = proDataunit;
    }
}