package com.unbank.mybatis.vo;

public class BhiPlant {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_plant.plant_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String plantWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.id
	 * @return  the value of bhi_plant.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.id
	 * @param id  the value for bhi_plant.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_department
	 * @return  the value of bhi_plant.plant_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantDepartment() {
		return plantDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_department
	 * @param plantDepartment  the value for bhi_plant.plant_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantDepartment(String plantDepartment) {
		this.plantDepartment = plantDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_people
	 * @return  the value of bhi_plant.plant_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantPeople() {
		return plantPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_people
	 * @param plantPeople  the value for bhi_plant.plant_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantPeople(String plantPeople) {
		this.plantPeople = plantPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_people_job
	 * @return  the value of bhi_plant.plant_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantPeopleJob() {
		return plantPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_people_job
	 * @param plantPeopleJob  the value for bhi_plant.plant_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantPeopleJob(String plantPeopleJob) {
		this.plantPeopleJob = plantPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_tel
	 * @return  the value of bhi_plant.plant_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantTel() {
		return plantTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_tel
	 * @param plantTel  the value for bhi_plant.plant_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantTel(String plantTel) {
		this.plantTel = plantTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_fax
	 * @return  the value of bhi_plant.plant_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantFax() {
		return plantFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_fax
	 * @param plantFax  the value for bhi_plant.plant_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantFax(String plantFax) {
		this.plantFax = plantFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_postcode
	 * @return  the value of bhi_plant.plant_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantPostcode() {
		return plantPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_postcode
	 * @param plantPostcode  the value for bhi_plant.plant_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantPostcode(String plantPostcode) {
		this.plantPostcode = plantPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_detail_address
	 * @return  the value of bhi_plant.plant_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantDetailAddress() {
		return plantDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_detail_address
	 * @param plantDetailAddress  the value for bhi_plant.plant_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantDetailAddress(String plantDetailAddress) {
		this.plantDetailAddress = plantDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_plant.plant_weburl
	 * @return  the value of bhi_plant.plant_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPlantWeburl() {
		return plantWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_plant.plant_weburl
	 * @param plantWeburl  the value for bhi_plant.plant_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPlantWeburl(String plantWeburl) {
		this.plantWeburl = plantWeburl;
	}
}