package com.unbank.mybatis.vo;

public class BhiPPP {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp.id
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp.info
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp.description
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp.id
     *
     * @return the value of bhi_ppp.id
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp.id
     *
     * @param id the value for bhi_ppp.id
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp.info
     *
     * @return the value of bhi_ppp.info
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp.info
     *
     * @param info the value for bhi_ppp.info
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp.description
     *
     * @return the value of bhi_ppp.description
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp.description
     *
     * @param description the value for bhi_ppp.description
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}