package com.unbank.mybatis.vo;

import java.util.Date;

public class BhiPro {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_name
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_area
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_time
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Date proTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_nature
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proNature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.firm_nature
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String firmNature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_trade
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proTrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_assets
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proAssets;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_stage
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proStage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_way
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_office
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proOffice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_cycle
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proCycle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_fund
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proFund;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.equipment_source
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String equipmentSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.governing_unit
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String governingUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.pro_facility
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String proFacility;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String weburl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_pro.type
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Byte type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.id
	 * @return  the value of bhi_pro.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.id
	 * @param id  the value for bhi_pro.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_name
	 * @return  the value of bhi_pro.pro_name
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProName() {
		return proName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_name
	 * @param proName  the value for bhi_pro.pro_name
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProName(String proName) {
		this.proName = proName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_area
	 * @return  the value of bhi_pro.pro_area
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProArea() {
		return proArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_area
	 * @param proArea  the value for bhi_pro.pro_area
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProArea(String proArea) {
		this.proArea = proArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_time
	 * @return  the value of bhi_pro.pro_time
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Date getProTime() {
		return proTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_time
	 * @param proTime  the value for bhi_pro.pro_time
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProTime(Date proTime) {
		this.proTime = proTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_nature
	 * @return  the value of bhi_pro.pro_nature
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProNature() {
		return proNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_nature
	 * @param proNature  the value for bhi_pro.pro_nature
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProNature(String proNature) {
		this.proNature = proNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.firm_nature
	 * @return  the value of bhi_pro.firm_nature
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getFirmNature() {
		return firmNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.firm_nature
	 * @param firmNature  the value for bhi_pro.firm_nature
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setFirmNature(String firmNature) {
		this.firmNature = firmNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_trade
	 * @return  the value of bhi_pro.pro_trade
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProTrade() {
		return proTrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_trade
	 * @param proTrade  the value for bhi_pro.pro_trade
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProTrade(String proTrade) {
		this.proTrade = proTrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_assets
	 * @return  the value of bhi_pro.pro_assets
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProAssets() {
		return proAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_assets
	 * @param proAssets  the value for bhi_pro.pro_assets
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProAssets(String proAssets) {
		this.proAssets = proAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_stage
	 * @return  the value of bhi_pro.pro_stage
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProStage() {
		return proStage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_stage
	 * @param proStage  the value for bhi_pro.pro_stage
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProStage(String proStage) {
		this.proStage = proStage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_way
	 * @return  the value of bhi_pro.pro_way
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProWay() {
		return proWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_way
	 * @param proWay  the value for bhi_pro.pro_way
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProWay(String proWay) {
		this.proWay = proWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_office
	 * @return  the value of bhi_pro.pro_office
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProOffice() {
		return proOffice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_office
	 * @param proOffice  the value for bhi_pro.pro_office
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProOffice(String proOffice) {
		this.proOffice = proOffice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_cycle
	 * @return  the value of bhi_pro.pro_cycle
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProCycle() {
		return proCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_cycle
	 * @param proCycle  the value for bhi_pro.pro_cycle
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProCycle(String proCycle) {
		this.proCycle = proCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_fund
	 * @return  the value of bhi_pro.pro_fund
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProFund() {
		return proFund;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_fund
	 * @param proFund  the value for bhi_pro.pro_fund
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProFund(String proFund) {
		this.proFund = proFund;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.equipment_source
	 * @return  the value of bhi_pro.equipment_source
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getEquipmentSource() {
		return equipmentSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.equipment_source
	 * @param equipmentSource  the value for bhi_pro.equipment_source
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setEquipmentSource(String equipmentSource) {
		this.equipmentSource = equipmentSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.governing_unit
	 * @return  the value of bhi_pro.governing_unit
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getGoverningUnit() {
		return governingUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.governing_unit
	 * @param governingUnit  the value for bhi_pro.governing_unit
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setGoverningUnit(String governingUnit) {
		this.governingUnit = governingUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.address
	 * @return  the value of bhi_pro.address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.address
	 * @param address  the value for bhi_pro.address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.pro_facility
	 * @return  the value of bhi_pro.pro_facility
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getProFacility() {
		return proFacility;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.pro_facility
	 * @param proFacility  the value for bhi_pro.pro_facility
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setProFacility(String proFacility) {
		this.proFacility = proFacility;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.weburl
	 * @return  the value of bhi_pro.weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getWeburl() {
		return weburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.weburl
	 * @param weburl  the value for bhi_pro.weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setWeburl(String weburl) {
		this.weburl = weburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_pro.type
	 * @return  the value of bhi_pro.type
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_pro.type
	 * @param type  the value for bhi_pro.type
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setType(Byte type) {
		this.type = type;
	}
}