package com.unbank.mybatis.vo;

public class BhiPrimaryDesign {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_primary_design.primary_design_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String primaryDesignWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.id
	 * @return  the value of bhi_primary_design.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.id
	 * @param id  the value for bhi_primary_design.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_department
	 * @return  the value of bhi_primary_design.primary_design_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignDepartment() {
		return primaryDesignDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_department
	 * @param primaryDesignDepartment  the value for bhi_primary_design.primary_design_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignDepartment(String primaryDesignDepartment) {
		this.primaryDesignDepartment = primaryDesignDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_people
	 * @return  the value of bhi_primary_design.primary_design_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignPeople() {
		return primaryDesignPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_people
	 * @param primaryDesignPeople  the value for bhi_primary_design.primary_design_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignPeople(String primaryDesignPeople) {
		this.primaryDesignPeople = primaryDesignPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_people_job
	 * @return  the value of bhi_primary_design.primary_design_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignPeopleJob() {
		return primaryDesignPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_people_job
	 * @param primaryDesignPeopleJob  the value for bhi_primary_design.primary_design_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignPeopleJob(String primaryDesignPeopleJob) {
		this.primaryDesignPeopleJob = primaryDesignPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_tel
	 * @return  the value of bhi_primary_design.primary_design_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignTel() {
		return primaryDesignTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_tel
	 * @param primaryDesignTel  the value for bhi_primary_design.primary_design_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignTel(String primaryDesignTel) {
		this.primaryDesignTel = primaryDesignTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_fax
	 * @return  the value of bhi_primary_design.primary_design_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignFax() {
		return primaryDesignFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_fax
	 * @param primaryDesignFax  the value for bhi_primary_design.primary_design_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignFax(String primaryDesignFax) {
		this.primaryDesignFax = primaryDesignFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_postcode
	 * @return  the value of bhi_primary_design.primary_design_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignPostcode() {
		return primaryDesignPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_postcode
	 * @param primaryDesignPostcode  the value for bhi_primary_design.primary_design_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignPostcode(String primaryDesignPostcode) {
		this.primaryDesignPostcode = primaryDesignPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_detail_address
	 * @return  the value of bhi_primary_design.primary_design_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignDetailAddress() {
		return primaryDesignDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_detail_address
	 * @param primaryDesignDetailAddress  the value for bhi_primary_design.primary_design_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignDetailAddress(String primaryDesignDetailAddress) {
		this.primaryDesignDetailAddress = primaryDesignDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_primary_design.primary_design_weburl
	 * @return  the value of bhi_primary_design.primary_design_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getPrimaryDesignWeburl() {
		return primaryDesignWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_primary_design.primary_design_weburl
	 * @param primaryDesignWeburl  the value for bhi_primary_design.primary_design_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setPrimaryDesignWeburl(String primaryDesignWeburl) {
		this.primaryDesignWeburl = primaryDesignWeburl;
	}
}