package com.unbank.mybatis.vo;

public class BhiSurvey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyPeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyPeopleJob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyPostcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_survey.survey_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	private String surveyWeburl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.id
	 * @return  the value of bhi_survey.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.id
	 * @param id  the value for bhi_survey.id
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_department
	 * @return  the value of bhi_survey.survey_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyDepartment() {
		return surveyDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_department
	 * @param surveyDepartment  the value for bhi_survey.survey_department
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyDepartment(String surveyDepartment) {
		this.surveyDepartment = surveyDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_people
	 * @return  the value of bhi_survey.survey_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyPeople() {
		return surveyPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_people
	 * @param surveyPeople  the value for bhi_survey.survey_people
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyPeople(String surveyPeople) {
		this.surveyPeople = surveyPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_people_job
	 * @return  the value of bhi_survey.survey_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyPeopleJob() {
		return surveyPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_people_job
	 * @param surveyPeopleJob  the value for bhi_survey.survey_people_job
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyPeopleJob(String surveyPeopleJob) {
		this.surveyPeopleJob = surveyPeopleJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_tel
	 * @return  the value of bhi_survey.survey_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyTel() {
		return surveyTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_tel
	 * @param surveyTel  the value for bhi_survey.survey_tel
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyTel(String surveyTel) {
		this.surveyTel = surveyTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_fax
	 * @return  the value of bhi_survey.survey_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyFax() {
		return surveyFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_fax
	 * @param surveyFax  the value for bhi_survey.survey_fax
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyFax(String surveyFax) {
		this.surveyFax = surveyFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_postcode
	 * @return  the value of bhi_survey.survey_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyPostcode() {
		return surveyPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_postcode
	 * @param surveyPostcode  the value for bhi_survey.survey_postcode
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyPostcode(String surveyPostcode) {
		this.surveyPostcode = surveyPostcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_detail_address
	 * @return  the value of bhi_survey.survey_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyDetailAddress() {
		return surveyDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_detail_address
	 * @param surveyDetailAddress  the value for bhi_survey.survey_detail_address
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyDetailAddress(String surveyDetailAddress) {
		this.surveyDetailAddress = surveyDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_survey.survey_weburl
	 * @return  the value of bhi_survey.survey_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public String getSurveyWeburl() {
		return surveyWeburl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_survey.survey_weburl
	 * @param surveyWeburl  the value for bhi_survey.survey_weburl
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	public void setSurveyWeburl(String surveyWeburl) {
		this.surveyWeburl = surveyWeburl;
	}
}