package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiConstruction;
import com.unbank.mybatis.vo.BhiConstructionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiConstructionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int countByExample(BhiConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int deleteByExample(BhiConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int insert(BhiConstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int insertSelective(BhiConstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    List<BhiConstruction> selectByExample(BhiConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") BhiConstruction record, @Param("example") BhiConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_construction
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int updateByExample(@Param("record") BhiConstruction record, @Param("example") BhiConstructionExample example);
}