package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiEnvironmentalAssessment;
import com.unbank.mybatis.vo.BhiEnvironmentalAssessmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiEnvironmentalAssessmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int countByExample(BhiEnvironmentalAssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int deleteByExample(BhiEnvironmentalAssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int insert(BhiEnvironmentalAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int insertSelective(BhiEnvironmentalAssessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    List<BhiEnvironmentalAssessment> selectByExample(BhiEnvironmentalAssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") BhiEnvironmentalAssessment record, @Param("example") BhiEnvironmentalAssessmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_environmental_assessment
     *
     * @mbggenerated Tue Mar 31 15:11:14 GMT+08:00 2015
     */
    int updateByExample(@Param("record") BhiEnvironmentalAssessment record, @Param("example") BhiEnvironmentalAssessmentExample example);
}