package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiOwner;
import com.unbank.mybatis.vo.BhiOwnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiOwnerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int countByExample(BhiOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByExample(BhiOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insert(BhiOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insertSelective(BhiOwner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiOwner> selectByExample(BhiOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") BhiOwner record,
			@Param("example") BhiOwnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_owner
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") BhiOwner record,
			@Param("example") BhiOwnerExample example);
}