package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiOther;
import com.unbank.mybatis.vo.BhiOtherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiOtherMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int countByExample(BhiOtherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByExample(BhiOtherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insert(BhiOther record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insertSelective(BhiOther record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiOther> selectByExample(BhiOtherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") BhiOther record,
			@Param("example") BhiOtherExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_other
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") BhiOther record,
			@Param("example") BhiOtherExample example);
}