package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiPlant;
import com.unbank.mybatis.vo.BhiPlantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiPlantMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int countByExample(BhiPlantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByExample(BhiPlantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insert(BhiPlant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insertSelective(BhiPlant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiPlant> selectByExample(BhiPlantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") BhiPlant record,
			@Param("example") BhiPlantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_plant
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") BhiPlant record,
			@Param("example") BhiPlantExample example);
}