package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiPro;
import com.unbank.mybatis.vo.BhiProExample;
import com.unbank.mybatis.vo.BhiProWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiProMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int countByExample(BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByExample(BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insert(BhiProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insertSelective(BhiProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiProWithBLOBs> selectByExampleWithBLOBs(BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiPro> selectByExample(BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	BhiProWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") BhiProWithBLOBs record,
			@Param("example") BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") BhiProWithBLOBs record,
			@Param("example") BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") BhiPro record,
			@Param("example") BhiProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(BhiProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByPrimaryKeyWithBLOBs(BhiProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_pro
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByPrimaryKey(BhiPro record);
}