package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiPPP;
import com.unbank.mybatis.vo.BhiPPPExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiPPPMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int countByExample(BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int deleteByExample(BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int insert(BhiPPP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int insertSelective(BhiPPP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    List<BhiPPP> selectByExampleWithBLOBs(BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    List<BhiPPP> selectByExample(BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    BhiPPP selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") BhiPPP record, @Param("example") BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int updateByExampleWithBLOBs(@Param("record") BhiPPP record, @Param("example") BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int updateByExample(@Param("record") BhiPPP record, @Param("example") BhiPPPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(BhiPPP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp
     *
     * @mbggenerated Thu Jul 14 13:55:45 GMT+08:00 2016
     */
    int updateByPrimaryKeyWithBLOBs(BhiPPP record);
}