package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiPrimaryDesign;
import com.unbank.mybatis.vo.BhiPrimaryDesignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiPrimaryDesignMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int countByExample(BhiPrimaryDesignExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByExample(BhiPrimaryDesignExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insert(BhiPrimaryDesign record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insertSelective(BhiPrimaryDesign record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiPrimaryDesign> selectByExample(BhiPrimaryDesignExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") BhiPrimaryDesign record,
			@Param("example") BhiPrimaryDesignExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_primary_design
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") BhiPrimaryDesign record,
			@Param("example") BhiPrimaryDesignExample example);
}