package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiSurvey;
import com.unbank.mybatis.vo.BhiSurveyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiSurveyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int countByExample(BhiSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int deleteByExample(BhiSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insert(BhiSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int insertSelective(BhiSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	List<BhiSurvey> selectByExample(BhiSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") BhiSurvey record,
			@Param("example") BhiSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_survey
	 * @mbggenerated  Tue Mar 31 15:11:14 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") BhiSurvey record,
			@Param("example") BhiSurveyExample example);
}